Create README.md
jayesh-parmar/inventory-management pull request #10
Opened 2023-08-28 03:26 UTC by jayesh-parmar

Create  Readme File  and add How To install project stap by stap

2023-08-28 08:17 UTC, dineshram7660 requested changes

2023-08-28 08:17 UTC, dineshram7660 commented on README.md
> +- login user
```suggestion
##  Laravel + Tailwind Css Admin Project 
- login user 
```

2023-08-28 08:17 UTC, dineshram7660 commented on README.md
> +- logout user
a work kare che joy lejo no hoy to new pr api dejo logout mate

2023-08-28 08:17 UTC, dineshram7660 commented on README.md
> +- password : admin123
```suggestion
- email: admin@gmail.com
- password : admin123
```

2023-08-28 08:18 UTC, dineshram7660 commented
# Retail ERP

### Documentation
- https://www.notion.so/ERP-Development-Specifications-5a45ec1eaf4945a39c16cc5b777c6b12
We use Notion to record all tasks and track progress. Bugs/features/updates all should be recorded in Notion.

1) If you're discussing something with a team member or decision makers, record the important notes/ideas in a Notion task.
2) If updates in your code affects other files,
    i) Either make the necessary changes right away when it's needs to be deployed together or short in nature
    ii) Add a Notion task with details and link it with the PR both ways.

TLDR: There is no harm in creating lots of Notion tasks even if they need to be archived later on. But a lot of potential loss of missing important stuff if one is lazy or over confident on memory.

### Technical

The information about the development process and reference details are recorded in [this file](Technical.md).

### Important notes for developers

- We are using OCI High availability MySQL instance in production. [It requires](https://docs.oracle.com/en-us/iaas/mysql-database/doc/prerequisites1.html#GUID-CC4B1DEC-9C52-4387-83CB-188F0454BCFA) that all the tables in the database must have primary keys. The pivot tables in the Laravel app do not require a primary key but we are adding `invisible_id` as INVISIBLE column to support the OCI requirements. Please add `invisible_id` as primary key in new pivot tables.

```
$table->id('invisible_id')->invisible();
```

### Requirements

- PHP 8.2
- Other [Laravel requirements](https://laravel.com/docs/9.x/deployment#server-requirements)

### Installation

- Clone the repo:
`git clone [REPO_URL] [DIRECTORY_NAME]`

- Create `.env` file from the example file:
`php -r "file_exists('.env') || copy('.env.example', '.env');"`

- Setup .env variables (Especially SANCTUM_STATEFUL_DOMAINS should be set. The value should be the domain name without 'http://' and a trailing slash. And `LIST_OF_WEB_APP_URLS_AND_KEYS` should be updated in all the sites.)

- Install the dependencies: `composer install`

- Generate Key: `php artisan key:generate`

- DB migrate: `php artisan migrate`

- Public images: `php artisan storage:link`

- Set the `LOG_CHANNEL` to `production_stack` and specify the `LOG_SLACK_WEBHOOK_URL` if you wish to receive log entries in Slack.

- NPM: `npm install`

- `npm run dev` and start developing...

- Note: For the production just run the `npm run build` command

- Install [redis](https://www.digitalocean.com/community/tutorials/how-to-install-and-secure-redis-on-ubuntu-22-04) and [phpredis](https://github.com/phpredis/phpredis):
    ```shell
      sudo apt install -y redis-server
      sudo nano /etc/redis/redis.conf
   ```
    - Configure redis as follows:

    ```editorconfig
    . . .

    # If you run Redis from upstart or systemd, Redis can interact with your
    # supervision tree. Options:
    #   supervised no      - no supervision interaction
    #   supervised upstart - signal upstart by putting Redis into SIGSTOP mode
    #   supervised systemd - signal systemd by writing READY=1 to $NOTIFY_SOCKET
    #   supervised auto    - detect upstart or systemd method based on
    #                        UPSTART_JOB or NOTIFY_SOCKET environment variables
    # Note: these supervision methods only signal "process is ready."
    #       They do not enable continuous liveness pings back to your supervisor.
    supervised systemd

    . . .
    ```
    - Restart `redis`
    ```shell
    sudo systemctl restart redis.service
    ```

    - Test `redis`
    ```shell
    redis-cli
    ```
    - In the prompt that follows, test connectivity with the `ping` command and you should get `pong` response.

- Install [pickle](https://github.com/FriendsOfPHP/pickle):
```shell
wget https://github.com/FriendsOfPHP/pickle/releases/latest/download/pickle.phar
```
- Now install `phpredis` and use all the default settings.
```shell
sudo php pickle.phar install redis
```
- Setup Horizon(Add Daemon Process), and set .env variables accordingly.

- To allow to upload big size files run below commands from terminal.
```shell
    sudo sed -i "s/upload_max_filesize = .*/upload_max_filesize = 20M/" /etc/php/8.2/fpm/php.ini # Default: 2MB
    sudo sed -i "s/upload_max_filesize = .*/upload_max_filesize = 20M/" /etc/php/8.2/cli/php.ini # Default: 2MB
    sudo sed -i "s/post_max_size = .*/post_max_size = 30M/" /etc/php/8.2/fpm/php.ini # Default: 8MB This value must be larger than upload_max_filesize and lower than memory_limit
    sudo sed -i "s/post_max_size = .*/post_max_size = 30M/" /etc/php/8.2/cli/php.ini # Default: 8MB This value must be larger than upload_max_filesize and lower than memory_limit
    sudo sed -i -e 's/memory_limit = .*/memory_limit = 4096M/g' /etc/php/8.2/cli/php.ini # Default: 128MB
    sudo sed -i -e 's/memory_limit = .*/memory_limit = 4096M/g' /etc/php/8.2/fpm/php.ini # Default: 128MB
```

- If your any of the request will take longer time to execute operation run below commands to increase the execution time.
```shell
    sudo sed -i "s/max_execution_time = .*/max_execution_time = 1200/" /etc/php/8.2/fpm/php.ini # Default: 30 seconds
    sudo sed -i "s/max_execution_time = .*/max_execution_time = 1200/" /etc/php/8.2/cli/php.ini # Default: 30 seconds

    sudo sed -i "s/request_terminate_timeout = .*/request_terminate_timeout = 1200/" /etc/php/8.2/fpm/pool.d/www.conf # Default: Off (0)

    test -f /etc/nginx/conf.d/timeout.conf && echo "timeout.conf file already exists." || (sudo touch /etc/nginx/conf.d/timeout.conf && echo 'fastcgi_read_timeout 1200;' | sudo tee --append /etc/nginx/conf.d/timeout.conf) # Create timeout configuration file if not exists

    # To change the value of fastcgi_read_timeout. But, If you are setting up for the first time and you have fired above command this command is not required.
    sudo sed -i "s/fastcgi_read_timeout .*/fastcgi_read_timeout 1200;/" /etc/nginx/conf.d/timeout.conf # Default: 60 seconds
```

- We are using [Laravel Passport](https://laravel.com/docs/10.x/passport) for app authentication. Please run the following command to generate the keys required by the underlying library: `php artisan passport:keys`

- For the backward compatibility we are allowing personal access token for the `Member Application` and `POS Application` API's. For that you need to run `php artisan passport:client --personal`

- We need to increase the `client_max_body_size` of nginx to allow file uploads. Please add the following line in the the `/etc/nginx/nginx.conf` file's http directive:
    `client_max_body_size 50M;`

- We are using [Browsershot](https://github.com/spatie/browsershot) to generate PDF files. You may use the following commands to install the required dependencies. It also install NodeJS. You may skip first line and `nodejs` install command if it is already installed.
    ```
    sudo apt-get install -y nodejs gconf-service libasound2 libatk1.0-0 libc6 libcairo2 libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgbm1 libgcc1 libgconf-2-4 libgdk-pixbuf2.0-0 libglib2.0-0 libgtk-3-0 libnspr4 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 ca-certificates fonts-liberation libappindicator1 libnss3 lsb-release xdg-utils wget libgbm-dev
    ```

- Timezone changed to MYT:
    - Forge > Server > Meta > Timezone (Running this command updates the server timezone. No need to fire the next command when forge is available)
    - (If you have done the change via forge, no need to follow this line) Server level - `sudo timedatectl set-timezone Asia/Kuala_Lumpur` (Command to check current timezone - `timedatectl`)
    - Laravel - application timezone is set to `Asia/Kuala_Lumpur` in the config file.
    - MySQL and PHP timezone depends on the server timezone. Just reload PHP FPM & MySQL services.
    - If there is a separate server for MySQL, you need to set the server ti [...]

2023-08-28 08:19 UTC, dineshram7660 commented
check this example

2023-08-29 05:49 UTC, dineshram7660 requested changes

2023-08-29 05:49 UTC, dineshram7660 commented on README.md
> +- We are using OCI High availability MySQL instance in production. It requires that all the tables in the database must have primary keys.
not requiring now plz remove this

2023-08-29 05:49 UTC, dineshram7660 commented on README.md
> +- The information about the development process and reference details are recorded in <a href="https://github.com/jayesh-parmar/inventory-management/compare/Technical.md?expand=1" >this file</a>
This file not now in over project so remove this

2023-08-29 05:49 UTC, dineshram7660 commented on README.md
> +- We are using OCI High availability MySQL instance in production. It requires that all the tables in the database must have primary keys.
this not required now please remove this

2023-08-29 05:49 UTC, dineshram7660 commented
hu tamne kai file examplae apu to ama hoy amj nai mukva nu pan apde jarur hoy avu j leva nu

2023-08-29 10:49 UTC, jayesh-parmar commented
👍

2023-08-29 11:08 UTC, merged