Admin theme
jayesh-parmar/inventory-management pull request #11
Opened 2023-08-28 04:52 UTC by jayesh-parmar

2023-08-28 08:21 UTC, dineshram7660 commented
please update the main to this branch

2023-08-29 10:48 UTC, jayesh-parmar commented
👍

2023-08-29 11:11 UTC, dineshram7660 requested changes

2023-08-29 11:11 UTC, dineshram7660 commented on resources/views/admin/layouts/nav.blade.php
> +                    <input class="w-full pl-8 pr-2 text-sm text-gray-700 placeholder-gray-600 bg-gray-100 border-0 rounded-md dark:placeholder-gray-500 dark:focus:shadow-outline-gray dark:focus:place
```suggestion
                    <input 
                    	class="w-full pl-8 pr-2 text-sm text-gray-700 placeholder-gray-600 bg-gray-100 border-0 rounded-md dark:placeholder-gray-500 dark:focus:shadow-outline-gray dark:focus:placeholder-gray-600 dark:bg-gray-700 dark:text-gray-200 focus:placeholder-gray-500 focus:bg-white focus:border-purple-300 focus:outline-none focus:shadow-outline-purple form-input" 
                    	type="text" 
                    	placeholder="Search for projects" 
                    	aria-label="Search" 
                    />
```

2023-08-29 11:11 UTC, dineshram7660 commented on public/public/assets/js/init-alpine.js
> +    // if user already changed the theme, use it
remove comment

2023-08-29 11:11 UTC, dineshram7660 commented on public/public/assets/js/init-alpine.js
> +    // else return their preferences
remove comment

2023-08-29 11:11 UTC, dineshram7660 commented on public/public/assets/js/init-alpine.js
> +    // Modal
remove comment

2023-08-29 11:11 UTC, dineshram7660 commented on resources/views/admin/layouts/header.php
> +<!-- Desktop sidebar -->
remove comment

2023-08-29 11:11 UTC, dineshram7660 commented on resources/views/admin/layouts/nav.blade.php
> +                                </a>
remove now

2023-08-29 11:42 UTC, jayesh-parmar commented
👍

2023-08-29 12:09 UTC, dineshram7660 requested changes

2023-08-29 12:09 UTC, dineshram7660 commented on resources/views/admin/layouts/header.php
> +<!-- Desktop sidebar -->
this is not done

2023-08-29 12:53 UTC, dineshram7660 requested changes

2023-08-29 12:53 UTC, dineshram7660 commented on resources/views/admin/layouts/header.php
> +                <a class="inline-flex items-center w-full text-sm font-semibold text-gray-800 transition-colors duration-150 hover:text-gray-800 dark:hover:text-gray-200 dark:text-gray-100" href="ind
change url dashboard

2023-08-29 12:53 UTC, dineshram7660 commented on resources/views/admin/layouts/header.php
> +        </a>
this url not working please check

2023-08-31 06:37 UTC, merged