add rector phpstan and ecs
jayesh-parmar/inventory-management pull request #13
Opened 2023-08-29 10:45 UTC by jayesh-parmar

2023-08-29 10:49 UTC, jayesh-parmar commented
👍

2023-08-29 11:20 UTC, dineshram7660 commented
please check all details how to run and setup rector

2023-08-31 07:27 UTC, jayesh-parmar commented
👍

2023-08-31 08:03 UTC, hirenkeraliya requested changes

2023-08-31 08:03 UTC, hirenkeraliya commented on rector.php
> +    ]);
Add more sets.

2023-08-31 09:32 UTC, dineshram7660 requested changes

2023-08-31 09:32 UTC, dineshram7660 commented on tests/CreatesApplication.php
> -    /**
a kem delete karu che?

2023-08-31 09:49 UTC, hirenkeraliya reviewed
https://github.com/rectorphp/rector/blob/main/docs/rector_rules_overview.md

Check this list of sets.

2023-09-02 08:17 UTC, hirenkeraliya requested changes

2023-09-02 08:17 UTC, hirenkeraliya commented on rector.php
> +        PHPUnitSetList::PHPUNIT_CODE_QUALITY,
Still Missing
---
PSR_4
LARAVEL_ARRAY_STR_FUNCTION_TO_STATIC_CALL
LARAVEL_CODE_QUALITY
LARAVEL_LEGACY_FACTORIES_TO_CLASSES
ARRAY_STR_FUNCTIONS_TO_STATIC_CALL

Not required
---
PHP_70,
PHP_71,
PHP_72,
PHP_73,
PHP_74,
PHP_80,
PHP_81,
PHP_52,
PHP_53,
PHP_54,
PHP_55,
PHP_56,

Duplicate
---
PHP_82,

2023-09-12 12:50 UTC, closed without merging