change in brand
jayesh-parmar/inventory-management pull request #18
Opened 2023-09-18 06:41 UTC by jayesh-parmar

2023-09-18 10:23 UTC, rajan-parmar requested changes

2023-09-18 10:23 UTC, rajan-parmar commented on app/Http/Controllers/BrandController.php
>          $brand = Brand::paginate(10);
selected the required columns. changes all

2023-09-18 10:23 UTC, rajan-parmar commented on app/Http/Controllers/ColorController.php
>          $color = Color::find($colorId);
select columns

2023-09-18 10:23 UTC, rajan-parmar commented on app/Http/Requests/BrandRequest.php
> +
you can direct return & proper indentation

2023-09-18 10:23 UTC, rajan-parmar commented on resources/views/admin/pages/brands/form.blade.php
> +    <form action="{{route('brand.store')}}" method="post" class="mt-5">
it should be single `<form action` line

2023-09-18 12:48 UTC, rajan-parmar approved these changes

2023-09-19 05:10 UTC, gauravmak requested changes

2023-09-19 05:10 UTC, gauravmak commented on app/Http/Requests/BrandRequest.php
> +               ];
@jayesh-parmar Please take care with spacing everywhere

2023-09-19 06:56 UTC, merged