Size test
jayesh-parmar/inventory-management pull request #22
Opened 2023-09-29 09:56 UTC by jayesh-parmar

2023-10-02 15:03 UTC, jayesh-parmar commented
![Screenshot (35)](https://github.com/jayesh-parmar/inventory-management/assets/108548229/e435974e-7ab4-4b38-b725-e24897a5fd08)

2023-10-03 04:27 UTC, rajan-parmar requested changes

2023-10-03 04:27 UTC, rajan-parmar commented on tests/Feature/SizeControllerTest.php
> +    ]);
```suggestion
    $this->assertDatabaseHas('sizes', [
    'id' => $size->id,
        'name' => 'update 2022',
    ]);
```

2023-10-03 06:54 UTC, rajan-parmar approved these changes

2023-10-03 07:14 UTC, merged