Category test
jayesh-parmar/inventory-management pull request #27
Opened 2023-10-03 11:10 UTC by jayesh-parmar

2023-10-03 11:11 UTC, jayesh-parmar commented
![Screenshot (37)](https://github.com/jayesh-parmar/inventory-management/assets/108548229/ad2bf6aa-b75d-4fa3-adb1-2026011360b2)

2023-10-04 06:22 UTC, rajan-parmar requested changes

2023-10-04 06:22 UTC, rajan-parmar commented on tests/Feature/CategoryControllerTest.php
> +    userLogin();
add test for user can not delete if child category

2023-10-04 09:37 UTC, rajan-parmar approved these changes

2023-10-05 06:22 UTC, merged