create product test
jayesh-parmar/inventory-management pull request #28
Opened 2023-10-04 09:23 UTC by jayesh-parmar

2023-10-04 09:28 UTC, jayesh-parmar commented
![Screenshot (38)](https://github.com/jayesh-parmar/inventory-management/assets/108548229/44578b91-332c-448b-bbe2-8dbd88a26830)

2023-10-04 09:42 UTC, rajan-parmar requested changes

2023-10-04 09:42 UTC, rajan-parmar commented on database/factories/ProductFactory.php
> +            'color_id' => Color::factory(),
```suggestion
            'brand_id' => Brand::factory()->create()->id,
            'size_id' => Size::factory()->create()->id,
            'color_id' => Color::factory()->create()->id,
```

2023-10-04 09:42 UTC, rajan-parmar commented on tests/Feature/ColorControllerTest.php
>      ]);
it's required to change?

2023-10-04 09:42 UTC, rajan-parmar commented on tests/Feature/ProductTest.php
> +    ]);
why use product factory. just required factory.
make command array to use in pass for route & database checking. because common data type two times.

2023-10-04 09:42 UTC, rajan-parmar commented on tests/Feature/ProductTest.php
> +        'status' => '0',
```suggestion
        'status' => true/false,
```

2023-10-04 11:01 UTC, rajan-parmar requested changes

2023-10-04 11:01 UTC, rajan-parmar commented on tests/Feature/ProductTest.php
>      $product = Product::factory()->create();
why use product factory? 
use respective factory

2023-10-04 11:01 UTC, rajan-parmar commented on tests/Feature/ProductTest.php
>      $product = Product::factory()->create();
product factory ma static value seed karo ane pachi value ene update karvani try karo jethi update that che khyal ave.

2023-10-05 04:12 UTC, rajan-parmar requested changes

2023-10-05 04:12 UTC, rajan-parmar commented on tests/Feature/ProductTest.php
> +    ]);
make variable for command array data.

2023-10-05 04:12 UTC, rajan-parmar commented on tests/Feature/ProductTest.php
> +
add test cases that required filed missing in the request than getting validation error.

2023-10-05 05:43 UTC, jayesh-parmar commented
![Screenshot (40)](https://github.com/jayesh-parmar/inventory-management/assets/108548229/f1f6153e-190f-44de-989b-0dcd616b2589)

2023-10-05 06:05 UTC, rajan-parmar approved these changes

2023-10-05 06:23 UTC, merged