attach categories with product test
jayesh-parmar/inventory-management pull request #30
Opened 2023-10-05 10:43 UTC by jayesh-parmar

2023-10-05 11:16 UTC, rajan-parmar requested changes

2023-10-05 11:16 UTC, rajan-parmar commented on tests/Feature/ProductTest.php
> +    ->assertRedirect(route('product.index'));
instead of merging the categoryIds, add in the same array.

2023-10-05 11:16 UTC, rajan-parmar commented on tests/Feature/ProductTest.php
> +    $this->assertDatabaseHas('products', $productData);
check category attach with product or not in the database.

2023-10-06 04:39 UTC, rajan-parmar requested changes

2023-10-06 04:39 UTC, rajan-parmar commented on tests/Feature/ProductTest.php
> +        }
just check that one of the category_id is present. no need to check all ids

2023-10-06 06:00 UTC, rajan-parmar requested changes

2023-10-06 06:00 UTC, rajan-parmar commented on tests/Feature/ProductTest.php
> +              $product->categories->whereIn('id', $categoryIds)->isNotEmpty());
use assertDatabaseHas but just check first category id only.

2023-10-06 07:47 UTC, rajan-parmar requested changes

2023-10-06 07:47 UTC, rajan-parmar commented on tests/Feature/ProductTest.php
> +    ]);
$categories = Category::factory(3)->create();

this give you the collection so play with this. passing only category Ids & same check first for database has id.

2023-10-06 09:00 UTC, rajan-parmar requested changes

2023-10-06 09:00 UTC, rajan-parmar commented on tests/Feature/ProductTest.php
> +
map ni jarur nathi.

2023-10-09 04:54 UTC, rajan-parmar requested changes

2023-10-09 04:54 UTC, rajan-parmar commented on tests/Feature/ProductTest.php
> +    $categoryIds = explode(',', $string);
why explode?
use https://laravel.com/docs/10.x/collections#method-implode

2023-10-09 04:55 UTC, rajan-parmar requested changes

2023-10-09 04:55 UTC, rajan-parmar commented on tests/Feature/ProductTest.php
> +    $categoryIds = explode(',', $string);
why implode & explode required?

2023-10-09 05:18 UTC, jayesh-parmar commented on tests/Feature/ProductTest.php
> +    $categoryIds = explode(',', $string);
category id ne string ma covert karva mate

2023-10-09 10:28 UTC, rajan-parmar requested changes

2023-10-09 10:28 UTC, rajan-parmar commented on tests/Feature/ProductTest.php
> +          $product->categories->whereIn('id', $categoryIds)->isNotEmpty());
just check that one of the category id add in the pivot table.

2023-10-09 12:03 UTC, rajan-parmar approved these changes

2023-10-09 13:41 UTC, merged